services:
  pygeoapi:
    build: 
      context: .
    environment:
      - PYGEOAPI_URL=http://localhost:5000
    ports:
      - 5000:80
    # # Mounting allows for hot reloading during development.
    volumes:
      - ./templates/jsonld:/pygeoapi/pygeoapi/templates/jsonld
