services:
  pygeoapi:
    build: 
      context: .
    environment:
      - PYGEOAPI_URL=http://localhost:5000
    ports:
      - 5000:80
    # volumes:
    # # Mounting allows for hot reloading during development.
    # # We have to mount these all independently since if we mount the entire directory, it overrides other templates
    #   - ./templates/ornl-hydrolocation.j2:/pygeoapi/pygeoapi/templates/ornl-hydrolocation.j2
    #   - ./templates/usgs-hydrolocation.j2:/pygeoapi/pygeoapi/templates/usgs-hydrolocation.j2
    #   - ./templates/usgs-location-oriented.j2:/pygeoapi/pygeoapi/templates/usgs-location-oriented.j2