name: Run Jinja2 Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2

      - name: Run tests
        run: |
          python ./tests/runner.py

    # this is not a verified test so we want a neutrally response 
      - name: End workflow neutrally
        run: echo "Workflow finished."